// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdk_NfzKOc_b6IaVNRifp9GYYGAXQz7Uk',
    appId: '1:832893703449:web:8670926c587767b822a188',
    messagingSenderId: '832893703449',
    projectId: 'keep-looking-up',
    authDomain: 'keep-looking-up.firebaseapp.com',
    storageBucket: 'keep-looking-up.appspot.com',
    measurementId: 'G-9X8WHJVPL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRa5KG69GoTsdoz-2PJByEXCNVbuTP1NI',
    appId: '1:832893703449:android:583c2ea2c3c4f40f22a188',
    messagingSenderId: '832893703449',
    projectId: 'keep-looking-up',
    storageBucket: 'keep-looking-up.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7DcOhD1bU5MjIy3DdDBHJN_2-8w1ZyQQ',
    appId: '1:832893703449:ios:cda7033dabae2be622a188',
    messagingSenderId: '832893703449',
    projectId: 'keep-looking-up',
    storageBucket: 'keep-looking-up.appspot.com',
    androidClientId: '832893703449-6qq9845n9c6583jt3gqfpghnaep51hh1.apps.googleusercontent.com',
    iosClientId: '832893703449-s375ub2ke9bpbh1oass2m35ks8crki3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.spaceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7DcOhD1bU5MjIy3DdDBHJN_2-8w1ZyQQ',
    appId: '1:832893703449:ios:cda7033dabae2be622a188',
    messagingSenderId: '832893703449',
    projectId: 'keep-looking-up',
    storageBucket: 'keep-looking-up.appspot.com',
    androidClientId: '832893703449-6qq9845n9c6583jt3gqfpghnaep51hh1.apps.googleusercontent.com',
    iosClientId: '832893703449-s375ub2ke9bpbh1oass2m35ks8crki3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.spaceApp',
  );
}
